### ISSUE TITLE
Critical Issue: Unknown Error Crash

### ISSUE THREAD

**Issue by soulus98** [soulus98/PoGo-profile-level-scanner#20]
Happens about 10% of the time on a single post and 50% on a multi-post

Happens at 'loading language traineddata (from cache)' 
progress: 0.5
```
\node_modules\tesseract.js\src\createWorker.js:173
        throw Error(data);
        ^

Error: Error: UNKNOWN: unknown error, open '\eng.traineddata'
    at ChildProcess.<anonymous> (\node_modules\tesseract.js\src\createWorker.js:173:15)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by soulus98** [comment]
Seems to happen less when saveLocalCopy is turned off, even less when on a dedicated server
